version: '3.8'

services:
  drive-uploader:
    build: .
    command: ["node", "src/index.js"]
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - /tmp:/tmp
    deploy:
      replicas: 1
      restart_policy:
        condition: any
