version: '3.8'

services:
  google-drive-uploader:
    build: 
      context: .
      dockerfile: Dockerfile
    image: google-drive-uploader:latest
    container_name: google-drive-uploader
    command: ["node","index.js"]
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - /tmp:/tmp
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    env_file:
      - .env
